### PR TITLE
Bump 2.8.0

### PR DESCRIPTION
**Pull request by AnasNaouchi**

### CODE REVIEW

**Review by danfowler — APPROVED** [review]

**Comment by aashishgurung** [comment]
I see we don't include PRs in the change log. Should we start doing it?

**Comment by danfowler** [comment]
@aashishgurung good idea

**Review by ajzkk — APPROVED** [review]

**Comment by aashishgurung** [comment]
@AnasNaouchi I was hoping to see somewhat like [this](https://github.com/omise/omise-magento/blob/develop/CHANGELOG.md). Current pattern will be troublesome if we have more than 1 PR in a release.

**Comment by AnasNaouchi** [comment]
> @AnasNaouchi I was hoping to see somewhat like [this](https://github.com/omise/omise-magento/blob/develop/CHANGELOG.md). Current pattern will be troublesome if we have more than 1 PR in a release.

Yeah but the PR number is the same for all 3 changes so that's why i added in the heading

**Comment by aashishgurung** [comment]
I see i's already merged. A better approach would be keeping the PR objective as the main point and adding other changes as sublists.

```
- Updated charge models to include `expired_at` field. ([#73](https://github.com/omise/omise-dotnet/pull/73))
   - Added `.example.env` and moved from static exposed values to `.env` usage
   - Changed unit testing to `dotnet test` instead of `nunit3-console.exe` removing third party dependency
```

Mentioning PR in the heading will bring inconsistency. We will have PR mentioned in the heading as well as in the body, when there are more PRs in a release.

**Pull request merged**
